"$schema" = 'https://starship.rs/config-schema.json'

format = """
$directory\
$sudo\
$python\
$fill\
$git_branch\
$git_commit\
$git_state\
$git_status
$shell\
$shlvl\
$status\
$character
"""

add_newline = true

# May change this in the future.
[status]
disabled       = false
success_style  = 'bold green'
success_symbol = "n/a"                    # This is only set to get status to appear on success.
format         = '[\[$status\]]($style) '

[character]
success_symbol = '[󰶻 ](bold green)'
error_symbol   = '[ ](bold red)'
# success_symbol = '[»](bold green)'
# success_symbol = '[󰄾 ](bold green)'
# success_symbol = '[ ](bold green)'
# success_symbol = '[ ](bold green)'
# success_symbol = '[󰄾 ](bold green)'
# error_symbol   = '[󱈸 ](bold red)'
# error_symbol   = '[! ](bold red)'

[directory]
style = 'bold italic blue'

[fill]
symbol = '─'
style  = 'bold #666666'

[git_branch]
format = ' on [$symbol$branch(:$remote_branch)]($style) '
symbol = " "

[git_status]
format    = '([\[ $all_status$ahead_behind\]]($style) )'
untracked = '[?$count](bold #cfcf15) '
modified  = '[!$count](bold #d4d481) '
staged    = '[+$count](bold #16a307) '
deleted   = '[✘$count](bold #ff0000) '
renamed   = '[»$count](bold #5551e0) '
stashed   = '[\$$count](bold #406291) '
ahead     = '[ $count](bold #741ca3) '
behind    = '[ $count](bold #741ca3) '
diverged  = '[ { ${ahead_count}  ${behind_count}}](bold #741ca3) '

[shell]
disabled       = false
bash_indicator = 'bash'
fish_indicator = 'fish'
zsh_indicator  = 'zsh'

[shlvl]
disabled  = false
threshold = 2
format    = '[$shlvl]($style) '

[sudo]
disabled = false
format   = '[\(as [$symbol](bold italic underline fg:#ffff00)\) ]($style)'
symbol   = 'root'

[python]
# Show currently active virtual environment.
format = '[(\($virtualenv\) )]($style)'
